version: "3.9"
services:
  web:
    build:
      # dockerfileが存在するディレクトリのパス
      context: ./typescript/simple-mercari-web
      # contextで指定したディレクトリ内のDockerfileの名前を指定
      dockerfile: dockerfile
    depends_on:
      - api
    ports:
      - "3000:3000"
    user: "trainee:mercari"
    # このURLをAPIエンドポイントとして使用する
    environment:
      REACT_APP_API_URL: "http://localhost:9000"
  api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "9000:9000"
    user: "trainee:mercari"
    environment:
      FRONT_URL: "http://localhost:3000"
