FROM node:20-alpine

RUN addgroup -S mercari && adduser -S trainee -G mercari

# dockerコンテナ内の作業ディレクトリ
WORKDIR /app
# /appの下にdockerfileが置かれているディレクトリの内容をコピー
COPY . .
RUN npm ci

RUN chown -R trainee:mercari /app
USER trainee

EXPOSE 3000
CMD ["npm", "start"]
